// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3HS_t0-H4d-l5E6u22MGysxun4xUWc3I',
    appId: '1:111728224667:web:bed4a36b6b91d725cd993e',
    messagingSenderId: '111728224667',
    projectId: 'exercise-app-prj',
    authDomain: 'exercise-app-prj.firebaseapp.com',
    storageBucket: 'exercise-app-prj.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3qfzJObIOzFtIJSg_SMN6uiwZDTOt9aA',
    appId: '1:111728224667:android:cbb81f828355dbf8cd993e',
    messagingSenderId: '111728224667',
    projectId: 'exercise-app-prj',
    storageBucket: 'exercise-app-prj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoauHjLu1D8HZtq6JUJcYJr2Gtrup5B1E',
    appId: '1:111728224667:ios:65db4f9f0cce33d2cd993e',
    messagingSenderId: '111728224667',
    projectId: 'exercise-app-prj',
    storageBucket: 'exercise-app-prj.firebasestorage.app',
    iosBundleId: 'com.example.exerciseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3HS_t0-H4d-l5E6u22MGysxun4xUWc3I',
    appId: '1:111728224667:web:a779190c8babfdb0cd993e',
    messagingSenderId: '111728224667',
    projectId: 'exercise-app-prj',
    authDomain: 'exercise-app-prj.firebaseapp.com',
    storageBucket: 'exercise-app-prj.firebasestorage.app',
  );

}